app.currency-client.enabled=${APP_CURRENCY_CLIENT_ENABLED}
app.currency-client.base-url=${APP_CURRENCY_CLIENT_BASE_URL}
app.currency-client.rate-path=${APP_CURRENCY_CLIENT_RATE_PATH}

app.currency-client.timeout.connect-timeout=${APP_CURRENCY_CLIENT_TIMEOUT_CONNECT_TIMEOUT}
app.currency-client.timeout.read-timeout=${APP_CURRENCY_CLIENT_TIMEOUT_READ_TIMEOUT}

app.currency-client.retry.max-attempts=${APP_CURRENCY_CLIENT_RETRY_MAX_ATTEMPTS}
app.currency-client.retry.wait-duration=${APP_CURRENCY_CLIENT_RETRY_WAIT_DURATION}

app.currency-client.rate-limiter.limit-for-period=${APP_CURRENCY_CLIENT_RATE_LIMITER_LIMIT_FOR_PERIOD}
app.currency-client.rate-limiter.limit-refresh-period=${APP_CURRENCY_CLIENT_RATE_LIMITER_LIMIT_REFRESH_PERIOD}
app.currency-client.rate-limiter.timeout-duration=${APP_CURRENCY_CLIENT_RATE_LIMITER_TIMEOUT_DURATION}

app.currency-client.health.enabled=${APP_CURRENCY_CLIENT_HEALTH_ENABLED}


# Environment variables example:
#
# APP_CURRENCY_CLIENT_ENABLED=true
# APP_CURRENCY_CLIENT_BASE_URL=https://api.frankfurter.dev
# APP_CURRENCY_CLIENT_RATE_PATH=/v2/rate
#
# APP_CURRENCY_CLIENT_TIMEOUT_CONNECT_TIMEOUT=5s
# APP_CURRENCY_CLIENT_TIMEOUT_READ_TIMEOUT=5s
#
# APP_CURRENCY_CLIENT_RETRY_MAX_ATTEMPTS=3
# APP_CURRENCY_CLIENT_RETRY_WAIT_DURATION=500ms
#
# APP_CURRENCY_CLIENT_RATE_LIMITER_LIMIT_FOR_PERIOD=10
# APP_CURRENCY_CLIENT_RATE_LIMITER_LIMIT_REFRESH_PERIOD=1s
# APP_CURRENCY_CLIENT_RATE_LIMITER_TIMEOUT_DURATION=0s
#
# APP_CURRENCY_CLIENT_HEALTH_ENABLED=true