spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/account_reservation}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
        exclude: env, shutdown
  endpoint:
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: false
  server:
    port: ${MANAGEMENT_PORT:8081}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${API_BASE_PATH:/api/v1}